[project]
name = "finmem"
version = "0.0.0"
description = ""
authors = [
    {name = "Haohang Li", email = "hli113@stevens.edu"}
]
requires-python = ">=3.10, <4.0"
dependencies = [
    "tqdm>=4.66.1,<5.0.0",
    "python-dotenv>=1.0.1,<2.0.0",
    "rich>=13.7.0,<14.0.0",
    "toml>=0.10.2,<0.11.0",
    "typer>=0.9.0,<0.10.0",
    "httpx>=0.26.0,<0.27.0",
    "sortedcontainers>=2.4.0,<3.0.0",
    "faiss-cpu>=1.7.4,<2.0.0",
    "guardrails-ai>=0.3.2,<0.4.0",
    "numpy>=1.26.3,<2.0.0",
    "annotated-types>=0.6.0,<0.7.0",
    "polars>=0.20.5,<0.21.0",
    "langchain-community>=0.0.15,<0.1.0",
    "torch>=2.2.0",
    "transformers>=4.37.2,<5.0.0",
    "pandas>=2.3.3",
    "yfinance>=1.0",
    "cleantext>=1.1.4",
    "levenshtein>=0.27.3",
    "pyarrow>=22.0.0",
    "langchain-together>=0.1.2",
    "pandas-stubs>=2.3.3.251219",
    "vadersentiment>=3.3.2",
    "matplotlib>=3.10.8",
]

[[tool.uv.index]]
name = "torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "torch-cpu" }
